server:
  port: 8001
mybatis:
  type-aliases-package: com.lx.cloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/clounddb01?useUnicode=true&characterEncoding=utf-8
    password: 123456
    username: root